[package]
name = "detect-inactive-mattermost"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
mattermost_api = "0.6.0"
passterm = "2.0.4"
serde = "1.0.215"
serde_derive = "1.0.215"
serde_json = "1.0.132"
tokio = { "version" = "1.41.1", "features" = ["full"] }

